eureka:
  client:
    fetchRegistry: true
    instance:
      preferIpAddress: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8777
spring:
  application:
    name: zuul-service
zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  routes:
    contact-service:
      path: /contactservice/**
      serviceId: contact-service
      stripPrefix: true
    user-service:
      path: /userservice/**
      serviceId: user-service
      stripPrefix: true
    zuul-service:
      path: /zuulservice/**
      serviceId: zuul-service
      stripPrefix: true
